### ISSUE TITLE
Allow override of input parameters

### ISSUE THREAD

**Issue by Sarafian** [Sarafian/ISHBootstrap#48]
To help install as template, some parameters are best that they are overrider in `Install-ISHDeployment.ps1`

```
$inputParameters=@{
machinename="mock"
baseurl="mock"
}
& .\Install-ISHDeployment.ps1 -InputParametersOverride $inputParameters
```

Script needs to use these values either by replacing the xml nodes or by creating new ones.

**Comment by beutepa** [comment]
Tested for v13.
